title:              data-driven
email:              michael.engel.85@googlemail.com
description:        A blog about value creation with data & AI
author:             Michael Engel
baseurl:            ""
url:                ""

# Social Profiles

linkedin_username: m-engel

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
